name: Run PHP CodeSniffer

# Run PHPCBF to fix changes then annotate PHPCS
# NB: Pull requests from forks do not have access to repository secrets so cannot commit changes.

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]

jobs:
  php-codesniffer:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ '8.4' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer, cs2pr
          extensions: zip

      - name: Install sponge
        run: sudo apt-get install moreutils

      - name: Run composer install
        run: composer install

      - name: Run PHPCBF to fix what it can
        continue-on-error: true
        run: vendor/bin/phpcbf

      - name: Run PHPCS to add annotations to the code
        continue-on-error: true
        run: vendor/bin/phpcs -q -n --report=checkstyle | cs2pr

      - name: Fail if there are still phpcs errors in the production code
        run: vendor/bin/phpcs includes

      - name: Commit PHPCBF changes
        if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' }}
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "ðŸ¤– PHPCBF"
